### ISSUE TITLE
null pointer error when sending a command to a light

### ISSUE THREAD

**Issue by fcastello** [pdf/golifx#7]
I am getting the following error when I send a command to the light.

`./lifx light color -H 65535 -S 0 -B 65535 -K 5500  -l Testing
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x177e60]

goroutine 129 [running]:
panic(0x21b640, 0x10626008)
	/usr/local/go/src/runtime/panic.go:500 +0x33c
github.com/pdf/golifx/protocol/v2/device.(*Device).Send.func1(0x106f0a40, 0x106f7580, 0x1071c000, 0x106, 0x106ec5a0)
	/Users/Pancho/workspace/src/github.com/pdf/golifx/protocol/v2/device/device.go:644 +0x180
created by github.com/pdf/golifx/protocol/v2/device.(*Device).Send
	/Users/Pancho/workspace/src/github.com/pdf/golifx/protocol/v2/device/device.go:670 +0x240`

I have compiled the utility for arm and running the command in a raspberry pi.
This happens sometimes and sometimes it doesn't and also happens in the Go code I am developing, but seems to randomly be doing it.

Let me know if you need more information. By the way, the command seems to be reaching the light because it is turning on or off or sending the color right. but I get this panic that prevents my Go code to keep running.

**Comment by fcastello** [comment]
Looked at line 644  in https://github.com/pdf/golifx/blob/master/protocol/v2/device/device.go and seems that in line 644
`if pktResponse.Result.GetType() == Acknowledgement {`

At the time pktResponse might be already cleaned up in other routine so it ends up pointing to something that doesn't exist anymore.
Anyway I am still getting familiar with the code and with Golang so any help would be appreciated

**Comment by pdf** [comment]
Sorry for the delay - I am out of the country currently, I will try to get back to you next week.

**Comment by pdf** [comment]
There are some outstanding bugs that I'm aware of, I'm going to try and get a refactor done in the next couple of weeks.

**Comment by pdf** [comment]
Please try v1.0.1 (beware the breaking change to subscriptions), and let me know if this is resolved, should you still be interested.

**Comment by pdf** [comment]
Closing due to inactivity, please feel free to re-open if this is still affecting you.
